language: java
jdk:
- oraclejdk11
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install: true
script: mvn clean install
before_deploy:
  - ./provision/upload_config.sh
  - ./provision/upload_image.sh
  - ./provision/upload_templates.sh
  - travis_wait 30 ./provision/deploy_stack.sh
deploy:
  provider: script
  script: bash ./provision/deploy_app.sh
  skip_cleanup: true
  on:
    branch: main
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - APPLICATION_NAME: brewery
  - AWS_DEFAULT_REGION: us-east-1
  - CONFIGURATION_BUCKET: brewery-configuration
  - APPLICATION_ENVIRONMENT: brewery-dev
  - AWS_DEFAULT_REGION: us-east-1
  - secure: NQGwjBL7mSQIJsYuJqaKUtRvCCtpPeRw58IdcCnlstrwR4Sp/p2YLjqz0y4XPkYTlBVcAwuQ3BsUU2Lbdg/fsCcNkwsNwhHhgoS+SAhE+9eh4650hTV5DxPz00QiwovzlS758CVHF6OCL0l1fjgeFbJmtFBkS1REPE3nVADV9ZKX7QytAa6020TE2P0A0bhItqwdFxSC5roAywbgslalwVl1aQfITTXgpJI056/rS1epuWhYuFoWh3IHvNgz2M0wLjaXTbz88J0PG7cX2ajAMs0Ti3lZAAs1naFYPPxJclX6jWlxeUNnWLJoOLXz02CpUxIho/hUEoVRCxJC52SaYdsiMSUoeUXwja/6biQTJtoREy4b0simIQIpQi4xEo3p2u45cwyLo/iXH5iIXADtnvvm6Vg61ZA8G0hLrpL1ek0gmYXLLLf1hpwI+uj1n9hGPhJ/v2y9gsSnvsfe/AhZMfPNVngLxOMUnevsogQpk6KNQDKj6MCd97ANDb7IS3GesfOf/RlC7jy5R3CHxM7V82MiuQh/XTiccu4NwSlZpkGRR80hXM6j9zKm7sRy+SZJaQ63ReNoVgjq0lZ6pIBH1fpXt8960NXRCPfF4uMTB9L2v54GqaLk+dZm0vbUHZY/mpea7dLtZvoxKiaKJqLINYPNh54ydc/Jkf2TMmX8HVY=
  - secure: BocQYVyYvX73Dccwj1TSjHjUCv6ssg2JYMe18GdtrDkCBPUf0+0cCfCyKMxYL3D9hL2Z5BNljm2drlU+s0XpSOjS8v36w5nyLpqMO3WVDrrMbcv1kVxCquo9uY44yDHZLsfp2TgayUgO6fyUZ3+7HLXyM3lUJLSQzdOJgVkUbkUXMd5eZMbhw58cw0N98WlreV2ZskTc2IH0pAi8re44v8E9QSSTxjOPj8PMno18SN3mdCsiEL87dX+8EEltZLgr1JaQLKBfD2EdEG2sUvLaDR2Qh0g5IX/9vm5+mmXEOYhWSOi/hmLWNSrVD3oFr8jbKvu9mPO2MTXDsviZbLviQbAOy4fb29kaXSToY4bLXH8Oca6giGouc1ISXF4qnzxnnK7DYdHhgQ5zOoLz2WCAqjHsZIzVkgX0yBkj9zodIH2ua3OaHy+/3W+Qnx2zsY4mSs9FdRUQkNin0ku/SdY35sIzk/TFWD9nC9T0DMJ6ztIIGlWWkT2IRl4h2dFy4csfzY7AEV5PfiWsgA2bQ4RVXcvE7r03kmQZTlGNyX5cfatvG4h90MxFxoun0Ga651YjoF8hwbx5lMIL1ply5tVxWC6fmyV4COZ97CRVoIq3hrkS2ZptbT/ffQ1AF3KdZN2QMG3z6mZBUMBLmWYs0LYHh6Sub/DwKNTl2nBQf4Xqems=
  - secure: bY7hc6SrSx6q/LRWRqbLjQD1lWG8JQgjccnskYXO95qP+NRwUVfKa3RMcdcoZ+3N5NFDky4Fqm/pgXYr8ZTucxmHSJdRfxfhkTbCCg3wiHd3Ye1x8tqX8QUjh7cEWZ+mPnsEf03vsUlQVFch6OOJMON6wfpfZDT6sWtAuMBAHzxbC+kjv+HAurbcJUcx86FBQITOAonpHVygqy4swuhxUskUXDP9cTRHcx9AbMOm0DGCliu1LDees2T7TwW12jK1rsyZmr0SHVMBtnKQ4Ayd0piBkcIvJ04Fh46y20Wyxy1YT1AR4EkobWsge1CGobkmFWuKDbPsXT/HazKQpNvq15Mt3Njl1Q+d4KoqN364MJ3ISe15QGgDX7QQpUyLzrG2v9edqclyFwFV3dJl0lLGwD+6pUXZXMKw2oaomfby8bFLl5uvaCTEoZjkbsWuG7o3OKkCv+dWDCn1+1QV1tdirEBoXq531yUQ1TLPu7iJoGNuBFj5VMhRIsG4wnij4Zp0NafynhUpuXt/QPUm2gWZJ0AqwuhSxJ/60YB/FUwj53QUR5jBvtgV+PxjTmSISTriUOYhWGYDMLBOJXeZDp/eeFzmC+Ju5xdA634PLToR2c33RbaPi0CCn2li9e3GxQGdcsQ2zeIn0bLO+i1tWMs/a9DhVNAVlcnCxzdyfDU7/i4=
  - secure: UwuYxH3Qnx9GCAHhSbyneTtYPQ8bEKaQ5/w54cYtL6IyNLMV1uxRPJ+yN2dFD2SdE2x4PyzgZzyHGTDkUBrf3lTZ9aa94wy5BPGo1DlMRvsXydM2mhUozC0jcAo3e+xIIshM3oZqVpPJOrzxjvJUdyo0nwEB2ePKOo3gv4vbJGvour8erZIVnEk54orTgAV8/nB4szcPbJ5jFVueQF07eL+pfnOesU3+uTjWxzFFWYU6ZlMyqdAJCNLdUkefNAaD//fimwGU8mh1/UbKcyMVYv/eSvTUeh1GP/8sfwjbXBtRt/OguitaT5pXs184vbY6tkTZKqLIGQxWFneBeEOmkAmyCjppn0k/j9eiD3XTutngCYNMsTQyJfKkqEqczF0fKxIpqvL95TvtgNoe4rsGRbFfOTOp1XkbSYL2vfFaytu4OdTwSBPjPoQbvGsYKvTIBav0vkcOzePVD9QYMaXhq2BojOCdgvtcJoSGtYkobRLY824T9QXA8HnaOPFsGjGeoFiOBkdctkGjEHnW3BLZWHo9MX/N/bEV5adgM+mqBphUdX06+I/hbzbs46sjPKQH9VE3OMBGVd6gUqR2o2vjb2ubxdhYT08FohdZe1o6dO2+qoD3BTAGB3RxKv1Zdy4y80UYRAPJVB64clmnYGnUXEAIyfvXuNWM5LINxiUfypU=
  - secure: eZtDTlY6X14iPiGNnomjRsNXjKCOKxGbJxgvl5yF50pNUTrHqeQja+buFxg6pi7frHux1AptUpTMQQkvgt0P0tlZY8efkaAQ9G4Tw0JzzP2iBnfxZBSNLiQscxuGLjGFX55sYGnUDKyBZBfVJOO/uGAM8QSy4AmaI2sX1cNGsZ0Z0dY0bMcphrWVF8BlJTabTw+lWEGrtgOM/R4DRi7clf1HL8S/s2+pwqzBPH4iKXnLMpVrOIrnSwcL+heW5EmKrttBeH80iuTVMTmdf9pz80TQPEm9K+tqzPOmhM16cK5kYSVa9HyXcNp/DmksPUrJt0ZQuhBe1aXybTVVmTVKwS/BVCryxiGbfZWgfxPw5n1u0vIXqxmk+XAp+zPyWzpgFbWUzHPk92HvD/gXWC01rFlNu1LlXwLDGDfzAnqXMZYZg/maok+ZVhcAbHbB+wnpxR10+X7vj0vrKfRreohTlJ0V+hu5PvJf3fcpglVEEojIQ+O3m3f8Af+9H6X9ok78ubBdDlFeDeb9oobYyrTPqZZLraMSXCNiD0icS+Y/Y0ZhMwumUQ1LJ+DUwPfnfr4Fl3MXRxy0EYd4TykjRIOzW5Y6O8VOBy6T4WU+SCZ/yRoL0WLf/CSuilKEmDvKpg8ZShvE/typTHkyF9C3jJIVm+qpKoSzv9fMmrtV9IPxN1I=
