---
AWSTemplateFormatVersion: 2010-09-09
Description: Route 53
Parameters:
  DomainName:
    Description: The domain name
    Type: String
  BeanstalkStackName:
    Description: Beanstalk stack name
    Type: String
Resources:
  SampleRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          Fn::ImportValue: !Sub "${BeanstalkStackName}-EnvironmentURL"
        HostedZoneId: Z3DZXE0Q79N41H
      HostedZoneId: Z02446671X8JP5661UWWB
      Name: !Ref DomainName
      Type: A
