server:
  port: 80
  error:
    whitelabel:
      enabled: false
security:
  oauth2:
    client:
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
    resource:
      tokenInfoUri: https://dev-8089486.okta.com/oauth2/default/v1/introspect
brewerydb:
  client:
    protocol: https
    host: api.openbrewerydb.org
    connectTimeout: 30000
    readTimeout: 240000
    connections:
      poolSize: 10
springdoc:
  swagger-ui.url: /open-api.yaml
  api-docs:
    enabled: false
